### ISSUE TITLE
how to support typescript?

### ISSUE THREAD

**Issue by clever-vpn** [condorheroblog/import-from-string#1]
Hi, 
   this package is very useful. by the way, how to set option for ts script?

**Comment by condorheroblog** [comment]
First, you need to convert your TypeScript code into a JavaScript string code that can be processed by `import-from-string`.

```js
// or webpack, esbuild etc.
import { buildBundler } from "import-from-string";
```

You can check out this link https://github.com/condorheroblog/bundle-import/blob/da93a9b5644984e60e105f098e970571952e7f6f/src/import.ts#L27
